[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript/tree/master/typescript", rev = "master" }

[[grammar]]
name = "tsx"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript/tree/master/typescript", rev = "master" }

[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript/tree/master/typescript", rev = "master" }

[[grammar]]
name = "jsx"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript/tree/master/typescript", rev = "master" }